title: "ИИ и Будущее"
description: "Блог о развитии искусственного интеллекта"
baseurl: "" # не меняй
url: ""     # не меняй

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
