title: "ИИ и Будущее"
description: "Блог о развитии искусственного интеллекта"
baseurl: "" # не меняй
url: ""     # не меняй

remote_theme: "niklasbuschmann/m10c"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
