title: "ИИ и Будущее"
description: "Блог о развитии искусственного интеллекта"
baseurl: "" # не меняй
url: ""     # не меняй

theme: https://github.com/LeNPaul/Millennial.git
plugins:
  - jekyll-remote-theme
