# --- Основные настройки сайта ---
title:               "Блог Дениса"
description:         "Минималистичный блог на Jekyll"
author:              "Денис"
email:               "your@email.com"
url:                 "https://denymoreno.github.io"
baseurl:             "" # оставить пустым, если используешь username.github.io

# --- Визуализация и генерация ---
markdown:            kramdown
highlighter:         rouge
permalink:           /:title/

# --- Плагины GitHub Pages ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# --- Пагинация ---
paginate:            5

# --- RSS ---
# Uncomment to use RSS instead of Atom
# feed:
#   path: rss-feed.xml
