# Site Build Settings

# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# RSS 2.0
#feed:
#  path: rss-feed.xml

# Site metadata
title: "DenyMoreno"
description: "максимум пользы от ресурса в виде блога"
author: "D"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

baseurl: "/myblog"
