disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'GTM-5DXTG4CS'

menu:
- {name: 'AI',   url: 'categories/ai'}
- {name: 'Live', url: 'categories/live'}

pagination:
  next_page: 'Следующие'
  previous_page: 'Предыдущие'

sharing_button_prompt: 'Поделись'
related_posts: 'Может быть интересным...'
post_date_prefix: 'Добавлено'
